version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
  - dependency-name: purgecss
    versions:
    - 3.1.3
    - 4.0.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
